- name: Voeg lokale host toe aan nextcloud groep
  hosts: localhost
  gather_facts: yes
  tasks:
    - name: Haal IP-adres op van huidige server
      debug:
        var: ansible_default_ipv4.address

    - name: Voeg IP-adres toe aan 'nextcloud' groep
      add_host:
        name: "{{ ansible_default_ipv4.address }}"
        groups: Nextcloud
        ansible_user: "{{ ansible_user }}"

- name: Install and configure Go, Docker, NATS, Janus, and Signaling Server
  hosts: localhost
  connection: local
  become: true
    
  tasks:

    - name: Installeer python3-pip als dat nog niet aanwezig is
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Install Docker SDK for Python
      pip:
        name: docker
        executable: pip3

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
